### ISSUE TITLE
ImportError: cannot import name 'newModel'

### ISSUE THREAD

**Issue by pawopawo** [HankKung/DistNAS-for-Semantic-Segmentation#1]
```
Traceback (most recent call last):
  File "train_autodeeplab.py", line 11, in <module>
    from modeling.deeplab import *
  File "/mnt/cephfs_new_wj/cv/xiaxin/NAS/nas_seg/DistNAS-for-Semantic-Segmentation/DistNAS-simple/modeling/deeplab.py", line 7, in <module>
    from modeling.backbone import build_backbone
  File "/mnt/cephfs_new_wj/cv/xiaxin/NAS/nas_seg/DistNAS-for-Semantic-Segmentation/DistNAS-simple/modeling/backbone/__init__.py", line 2, in <module>
    from new_model import newModel,get_default_net
ImportError: cannot import name 'newModel'
```

Thanks for your excellent work

When I run `train_cityscapes.sh` under the DistNAS-simple / folder, the above error is generated

**Comment by HankKung** [comment]
Hi thanks for your attention to this repo. Unfortunately, this repo is currently discarded. If you are interested in Auto-DeepLab, I'll suggest you take a look at https://github.com/NoamRosenberg/AutoML

It's the best implementation of Auto-DeepLab so far.
